version: '3'
services:
  web:
    image: "whreplay:latest"
    ports:
      - "5000:5000"
    volumes:
      - "/home/q/install/webhook-replay/replay.db:/whreplay/replay.db"
    deploy:
      restart_policy:
        condition: always
        delay: 5s
        max_attempts: 5
        window: 10s
